### ISSUE TITLE
[Tracking] 新C2A間通信に対応した GENERATE_TLM Cmdの実装

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#537]
## 概要
[Tracking] 新C2A間通信に対応した GENERATE_TLM Cmdの実装

## 詳細
- https://github.com/ut-issl/c2a-core/issues/247 の続きで実装のための tracking issue

task list
- [x] #538
  - https://github.com/ut-issl/c2a-core/issues/247#issuecomment-1465630067
  - ここではまずは tlm table の構造を変えない
- [x] https://github.com/ut-issl/c2a-core/issues/542
- [x] #539
  - https://github.com/ut-issl/c2a-core/issues/247#issuecomment-1465630067
- [x] #540
  - tlm table の構造を変更し， `Cmd_TG_GENERATE_TLM` では 2nd obc のテレメを生成できなくする
- [x] https://github.com/ut-issl/c2a-core/issues/543
- [ ] https://github.com/ut-issl/python-wings-interface/issues/33
- [x] #556
- [x] https://github.com/ut-issl/c2a-core/issues/582

## close条件
すべて close したら

**Comment by meltingrabbit** [comment]
- https://github.com/ut-issl/python-wings-interface/issues/33 


は別途おこなうとして，close
